apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-myapp
        image: ARTIFACT_REGISTRY_URL/python-myapp:latest
        ports:
        - containersPort: 8080